// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UwdASP.Data;

namespace UwdASP.Migrations
{
    [DbContext(typeof(UwdDbContext))]
    [Migration("20181218143749_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<long>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<long>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("UwdASP.Data.Models.Group", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<int>("Semester");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Programowanie Gr.1",
                            Semester = 7
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Sieci komputerowe Gr. 2",
                            Semester = 7
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Programowanie",
                            Semester = 6
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Programowanie",
                            Semester = 5
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Programowanie",
                            Semester = 4
                        });
                });

            modelBuilder.Entity("UwdASP.Data.Models.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Matematyka"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Fizyka"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Literatura"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Programowanie Java"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Programowanie C++"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Programowanie Python"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Infrastruktura sieci"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Bazy danych"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("UwdASP.Data.Models.Mark", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTimeOffset>("Date");

                    b.Property<long>("LessonId");

                    b.Property<string>("MarkType")
                        .IsRequired();

                    b.Property<long>("StudentDataId");

                    b.Property<long>("TeacherDataId");

                    b.Property<float>("Value");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentDataId");

                    b.HasIndex("TeacherDataId");

                    b.ToTable("Marks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Comment = "Bardzo dobrze",
                            Date = new DateTimeOffset(new DateTime(2018, 11, 9, 12, 34, 42, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            LessonId = 4L,
                            MarkType = "Regular",
                            StudentDataId = 1L,
                            TeacherDataId = 1L,
                            Value = 5f
                        },
                        new
                        {
                            Id = 2L,
                            Comment = "Elegancko",
                            Date = new DateTimeOffset(new DateTime(2018, 11, 10, 13, 5, 7, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            LessonId = 7L,
                            MarkType = "Regular",
                            StudentDataId = 1L,
                            TeacherDataId = 2L,
                            Value = 4.5f
                        },
                        new
                        {
                            Id = 3L,
                            Comment = "Elegancko",
                            Date = new DateTimeOffset(new DateTime(2018, 11, 10, 13, 5, 2, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            LessonId = 3L,
                            MarkType = "Regular",
                            StudentDataId = 8L,
                            TeacherDataId = 2L,
                            Value = 4.5f
                        },
                        new
                        {
                            Id = 4L,
                            Comment = "Wystarczy",
                            Date = new DateTimeOffset(new DateTime(2018, 11, 10, 13, 5, 9, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            LessonId = 5L,
                            MarkType = "Regular",
                            StudentDataId = 6L,
                            TeacherDataId = 3L,
                            Value = 3.5f
                        },
                        new
                        {
                            Id = 5L,
                            Comment = "Idealnie",
                            Date = new DateTimeOffset(new DateTime(2018, 11, 10, 13, 5, 9, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            LessonId = 3L,
                            MarkType = "Regular",
                            StudentDataId = 7L,
                            TeacherDataId = 3L,
                            Value = 5f
                        },
                        new
                        {
                            Id = 6L,
                            Comment = "Idealnie",
                            Date = new DateTimeOffset(new DateTime(2018, 11, 10, 13, 5, 9, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            LessonId = 5L,
                            MarkType = "Regular",
                            StudentDataId = 2L,
                            TeacherDataId = 3L,
                            Value = 5f
                        },
                        new
                        {
                            Id = 7L,
                            Comment = "No niestety",
                            Date = new DateTimeOffset(new DateTime(2018, 11, 10, 13, 5, 9, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            LessonId = 8L,
                            MarkType = "Regular",
                            StudentDataId = 3L,
                            TeacherDataId = 3L,
                            Value = 3f
                        },
                        new
                        {
                            Id = 8L,
                            Comment = "Idealnie",
                            Date = new DateTimeOffset(new DateTime(2018, 11, 10, 13, 5, 9, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            LessonId = 6L,
                            MarkType = "Regular",
                            StudentDataId = 6L,
                            TeacherDataId = 2L,
                            Value = 5f
                        });
                });

            modelBuilder.Entity("UwdASP.Data.Models.Presence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Date");

                    b.Property<long>("LessonId");

                    b.Property<long>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("Presences");
                });

            modelBuilder.Entity("UwdASP.Data.Models.Schedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("GroupId");

                    b.Property<long>("LessonId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("LessonId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("UwdASP.Data.Models.Specialization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Programowanie i bazy danych"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Sieci komputerowe"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Fizioterapia"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Zarządzanie"
                        });
                });

            modelBuilder.Entity("UwdASP.Data.Models.StudentData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Balance");

                    b.Property<int>("BankAccountNumber");

                    b.Property<long>("GroupId");

                    b.Property<int>("Index");

                    b.Property<int>("Semester");

                    b.Property<long>("SpecializationId");

                    b.Property<DateTime>("StudyBeginningDate");

                    b.Property<string>("StudyType")
                        .IsRequired();

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId");

                    b.ToTable("StudentsData");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Balance = 1500f,
                            BankAccountNumber = 123456789,
                            GroupId = 1L,
                            Index = 29282,
                            Semester = 7,
                            SpecializationId = 1L,
                            StudyBeginningDate = new DateTime(2015, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudyType = "Stationary",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Balance = 1650f,
                            BankAccountNumber = 123456789,
                            GroupId = 2L,
                            Index = 29283,
                            Semester = 7,
                            SpecializationId = 1L,
                            StudyBeginningDate = new DateTime(2015, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudyType = "Stationary",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Balance = -1300f,
                            BankAccountNumber = 123456789,
                            GroupId = 1L,
                            Index = 29284,
                            Semester = 7,
                            SpecializationId = 1L,
                            StudyBeginningDate = new DateTime(2015, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudyType = "Stationary",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Balance = 1337f,
                            BankAccountNumber = 123456789,
                            GroupId = 3L,
                            Index = 29285,
                            Semester = 7,
                            SpecializationId = 2L,
                            StudyBeginningDate = new DateTime(2015, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudyType = "Stationary",
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            Balance = 1337f,
                            BankAccountNumber = 123456789,
                            GroupId = 3L,
                            Index = 29285,
                            Semester = 7,
                            SpecializationId = 2L,
                            StudyBeginningDate = new DateTime(2015, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudyType = "Stationary",
                            UserId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            Balance = 9999f,
                            BankAccountNumber = 123456789,
                            GroupId = 4L,
                            Index = 29286,
                            Semester = 7,
                            SpecializationId = 1L,
                            StudyBeginningDate = new DateTime(2015, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudyType = "Stationary",
                            UserId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            Balance = 2400f,
                            BankAccountNumber = 123456789,
                            GroupId = 1L,
                            Index = 29287,
                            Semester = 7,
                            SpecializationId = 1L,
                            StudyBeginningDate = new DateTime(2015, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudyType = "Stationary",
                            UserId = 7L
                        },
                        new
                        {
                            Id = 8L,
                            Balance = 5000f,
                            BankAccountNumber = 123456789,
                            GroupId = 1L,
                            Index = 29288,
                            Semester = 7,
                            SpecializationId = 1L,
                            StudyBeginningDate = new DateTime(2015, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudyType = "Stationary",
                            UserId = 8L
                        });
                });

            modelBuilder.Entity("UwdASP.Data.Models.TeacherData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            UserId = 9L
                        },
                        new
                        {
                            Id = 2L,
                            UserId = 10L
                        },
                        new
                        {
                            Id = 3L,
                            UserId = 11L
                        });
                });

            modelBuilder.Entity("UwdASP.Data.Models.TeacherGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("GroupId");

                    b.Property<long?>("TeacherDataId");

                    b.Property<long>("TeacherId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TeacherDataId");

                    b.ToTable("TeacherGroups");
                });

            modelBuilder.Entity("UwdASP.Data.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("UserType")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a19a142c-9189-4eb0-a913-1b12a6db2960",
                            Email = "aandrieiev@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Andrieiev",
                            LastName = "Andrieiev",
                            LockoutEnabled = false,
                            NormalizedEmail = "AANDRIEIEV@GMAIL.COM",
                            NormalizedUserName = "AANDRIEIEV",
                            PasswordHash = "AQAAAAEAACcQAAAAEOOpPswo6zXXiFDEMwQspnDww6Snr9zfpos1vhE4/G3pIC+n5oju8r0QZmPaRG8NIw==",
                            PhoneNumber = "+48537018321",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "aandrieiev",
                            UserType = "Student"
                        },
                        new
                        {
                            Id = 2L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c620f2a-3497-4bfc-ad7f-51a48d192929",
                            Email = "dszewczenko@mail.ru",
                            EmailConfirmed = false,
                            FirstName = "Dmytro",
                            LastName = "Szewczenko",
                            LockoutEnabled = false,
                            NormalizedEmail = "DSZEWCZENKO@MAIL.RU",
                            NormalizedUserName = "DSZEWCZENKO",
                            PasswordHash = "AQAAAAEAACcQAAAAEOfJh3OtkYh+/HYBMVe7dTvAfd6Z0Sb0WauQGf398R0Y15m2Ug2/u2yZW6DpGYNDzg==",
                            PhoneNumber = "+4856433666",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "dszewczenko",
                            UserType = "Student"
                        },
                        new
                        {
                            Id = 3L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0aa62eb9-a7b3-4b0a-a2ae-258a3d0ce3a7",
                            Email = "mmorrison@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Mykhailo",
                            LastName = "Morrison",
                            LockoutEnabled = false,
                            NormalizedEmail = "MMORRISON@GMAIL.COM",
                            NormalizedUserName = "MMORRISON",
                            PasswordHash = "AQAAAAEAACcQAAAAEHFUDzwelRuLSbRdr7tUHEO8foPCziKbpLKcjybCbMq1zUL8VB0arh1Ec6GwAQ3vMA==",
                            PhoneNumber = "+4856666666",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mmorrison",
                            UserType = "Student"
                        },
                        new
                        {
                            Id = 4L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bf6f2d7a-69c3-447d-9b26-f226b2b96b9b",
                            Email = "srazovyi@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Serhii",
                            LastName = "Razovyi",
                            LockoutEnabled = false,
                            NormalizedEmail = "SRAZOVYI@GMAIL.COM",
                            NormalizedUserName = "SRAZOVYI",
                            PasswordHash = "AQAAAAEAACcQAAAAEAlNggkL1SdpH69qfJ17Aj9FER2O+nU5K02G8gXptvqD4uX0WhAz5UrnfbThgeSYOA==",
                            PhoneNumber = "+486565346521",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "srazovyi",
                            UserType = "Student"
                        },
                        new
                        {
                            Id = 5L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6a176f94-b837-4627-b1b9-cf352ab5600d",
                            Email = "mkowalska@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Matylda",
                            LastName = "Kowalska",
                            LockoutEnabled = false,
                            NormalizedEmail = "MKOWALSKA@GMAIL.COM",
                            NormalizedUserName = "MKOWALSKA",
                            PasswordHash = "AQAAAAEAACcQAAAAEEGGdu26i/AjvIvRGHotOwTFOL9ApZUljB/y0Ti5SXh76biPfflOKcVuIry0EJy8+w==",
                            PhoneNumber = "+48656534642",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mkowalska",
                            UserType = "Student"
                        },
                        new
                        {
                            Id = 6L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "78f29c30-6857-476a-b1ed-c680b9705001",
                            Email = "awawrzyniak@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Antonina",
                            LastName = "Wawrzyniak",
                            LockoutEnabled = false,
                            NormalizedEmail = "AWAWRZYNIAK@GMAIL.COM",
                            NormalizedUserName = "AWAWRZYNIAK",
                            PasswordHash = "AQAAAAEAACcQAAAAEM6yhNmTRxVx8jAoZmEPa+5S5Dgpacey2Pcd3h8G7qflvluJempuVFjFcXQEN8ppMw==",
                            PhoneNumber = "+4865653464",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "awawrzyniak",
                            UserType = "Student"
                        },
                        new
                        {
                            Id = 7L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a44aeb08-aa2d-47d7-889f-684aefc18ae7",
                            Email = "skarpiński@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Szymon",
                            LastName = "Karpiński",
                            LockoutEnabled = false,
                            NormalizedEmail = "SKARPIŃSKI@GMAIL.COM",
                            NormalizedUserName = "SKARPIŃSKI",
                            PasswordHash = "AQAAAAEAACcQAAAAEHHLxwLwmhKTzqhGxXqN+b8XiiQuBjeilzRBAp+6g5L654nf0VzSsZT2MWigeOTuhA==",
                            PhoneNumber = "+4865653465",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "skarpiński",
                            UserType = "Student"
                        },
                        new
                        {
                            Id = 8L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "edb004c6-36ef-450e-821e-b0b165dfa2b8",
                            Email = "kpawłowska@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Kinga",
                            LastName = "Pawłowska",
                            LockoutEnabled = false,
                            NormalizedEmail = "KPAWŁOWSKA@GMAIL.COM",
                            NormalizedUserName = "KPAWŁOWSKA",
                            PasswordHash = "AQAAAAEAACcQAAAAEP/5o9JzbOWIMKgI4eFraCQkDsiqXALc+8WW2kCGuHEdmd+gBpvL61SDsVmlynUSkg==",
                            PhoneNumber = "+4865653466",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "kpawłowska",
                            UserType = "Student"
                        },
                        new
                        {
                            Id = 9L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c02240f-df15-4b24-b427-c90fbb236eec",
                            Email = "krychlicki@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Kicior",
                            LastName = "Rychlicki",
                            LockoutEnabled = false,
                            NormalizedEmail = "KRYCHLICKI@GMAIL.COM",
                            NormalizedUserName = "KRYCHLICKI",
                            PasswordHash = "AQAAAAEAACcQAAAAELUCwbrVOV97MmTNQLSmnCckgDDznCRO1hzaoNRivlXZPo3V6oSwFO9jb5F9TxLruQ==",
                            PhoneNumber = "+486546546542",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "krychlicki",
                            UserType = "Teacher"
                        },
                        new
                        {
                            Id = 10L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c35a2569-312b-4098-b327-bf53e001019b",
                            Email = "aniewiamodmski@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Adam",
                            LastName = "Niewiamodmski",
                            LockoutEnabled = false,
                            NormalizedEmail = "ANIEWIADOMSKI@GMAIL.COM",
                            NormalizedUserName = "ANIEWIADOMSKI",
                            PasswordHash = "AQAAAAEAACcQAAAAEJHhbltBOF2AMCBxdLvyowGuOsuCxWs05yCGAXSpAOBJribUaiyMrFNLi5jjJ7MWXw==",
                            PhoneNumber = "+486542546443",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "aniewiamodmski",
                            UserType = "Teacher"
                        },
                        new
                        {
                            Id = 11L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a5b4d043-1484-4369-8bcb-e3fc201d9c94",
                            Email = "mkacperski@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Maciej",
                            LastName = "Kacperski",
                            LockoutEnabled = false,
                            NormalizedEmail = "MKACPERSKI@GMAIL.COM",
                            NormalizedUserName = "MKACPERSKI",
                            PasswordHash = "AQAAAAEAACcQAAAAEJEEc68UddY2rUucNDDNx+Wy1FaKc9Z1WL4P28wCsnNGtoP6utn2ZHmf8kpqtWx2Jw==",
                            PhoneNumber = "+489541543785",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "mkacperski",
                            UserType = "Teacher"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("UwdASP.Data.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("UwdASP.Data.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UwdASP.Data.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("UwdASP.Data.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UwdASP.Data.Models.Mark", b =>
                {
                    b.HasOne("UwdASP.Data.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UwdASP.Data.Models.StudentData", "StudentData")
                        .WithMany()
                        .HasForeignKey("StudentDataId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UwdASP.Data.Models.TeacherData", "TeacherData")
                        .WithMany()
                        .HasForeignKey("TeacherDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UwdASP.Data.Models.Presence", b =>
                {
                    b.HasOne("UwdASP.Data.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UwdASP.Data.Models.StudentData", "StudentData")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UwdASP.Data.Models.Schedule", b =>
                {
                    b.HasOne("UwdASP.Data.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UwdASP.Data.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UwdASP.Data.Models.StudentData", b =>
                {
                    b.HasOne("UwdASP.Data.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UwdASP.Data.Models.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UwdASP.Data.Models.User", "Identity")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UwdASP.Data.Models.TeacherData", b =>
                {
                    b.HasOne("UwdASP.Data.Models.User", "Identity")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UwdASP.Data.Models.TeacherGroup", b =>
                {
                    b.HasOne("UwdASP.Data.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UwdASP.Data.Models.TeacherData", "TeacherData")
                        .WithMany()
                        .HasForeignKey("TeacherDataId");
                });
#pragma warning restore 612, 618
        }
    }
}
